/* automatically generated by rust-bindgen 0.59.1 */

// Execute "bindgen ec.hpp" and add the incremental output to this file

pub const FCALL_ID_INVERSE_FP_EC: u32 = 1;
pub const FCALL_ID_INVERSE_FN_EC: u32 = 2;
pub const FCALL_ID_SQRT_FP_EC_PARITY: u32 = 3;

extern "C" {
    pub fn AddPointEc(
        _dbl: ::core::ffi::c_ulong,
        _x1: *const ::core::ffi::c_ulong,
        _y1: *const ::core::ffi::c_ulong,
        _x2: *const ::core::ffi::c_ulong,
        _y2: *const ::core::ffi::c_ulong,
        _x3: *mut ::core::ffi::c_ulong,
        _y3: *mut ::core::ffi::c_ulong,
    ) -> ::core::ffi::c_int;
}

extern "C" {
    pub fn AddPointEcP(
        _dbl: ::core::ffi::c_ulong,
        _p1: *const ::core::ffi::c_ulong,
        _p2: *const ::core::ffi::c_ulong,
        _p3: *mut ::core::ffi::c_ulong,
    ) -> ::core::ffi::c_int;
}

extern "C" {
    pub fn InverseFpEc(
        a: *const ::core::ffi::c_ulong,
        r: *mut ::core::ffi::c_ulong,
    ) -> ::core::ffi::c_int;
}

extern "C" {
    pub fn InverseFnEc(
        a: *const ::core::ffi::c_ulong,
        r: *mut ::core::ffi::c_ulong,
    ) -> ::core::ffi::c_int;
}

extern "C" {
    pub fn SqrtFpEcParity(
        a: *const ::core::ffi::c_ulong,
        parity: ::core::ffi::c_ulong,
        r: *mut ::core::ffi::c_ulong,
    ) -> ::core::ffi::c_int;
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct FcallContext {
    pub function_id: ::core::ffi::c_ulong,
    pub params_max_size: ::core::ffi::c_ulong,
    pub params_size: ::core::ffi::c_ulong,
    pub params: [::core::ffi::c_ulong; 32usize],
    pub result_max_size: ::core::ffi::c_ulong,
    pub result_size: ::core::ffi::c_ulong,
    pub result: [::core::ffi::c_ulong; 32usize],
}

extern "C" {
    // pub fn Fcall(ctx: *mut FcallContext) -> ::core::ffi::c_int;
    pub fn Fcall(ctx: *mut FcallContext) -> ::core::ffi::c_int;
}

extern "C" {
    pub fn InverseFpEcCtx(ctx: *mut FcallContext) -> ::core::ffi::c_int;
}

extern "C" {
    pub fn InverseFnEcCtx(ctx: *mut FcallContext) -> ::core::ffi::c_int;
}

extern "C" {
    pub fn SqrtFpEcParityCtx(ctx: *mut FcallContext) -> ::core::ffi::c_int;
}

extern "C" {
    pub fn Arith256(
        a: *const ::core::ffi::c_ulong,
        b: *const ::core::ffi::c_ulong,
        c: *const ::core::ffi::c_ulong,
        dl: *mut ::core::ffi::c_ulong,
        dh: *mut ::core::ffi::c_ulong,
    ) -> ::core::ffi::c_int;
}

extern "C" {
    pub fn Arith256Mod(
        a: *const ::core::ffi::c_ulong,
        b: *const ::core::ffi::c_ulong,
        c: *const ::core::ffi::c_ulong,
        module: *const ::core::ffi::c_ulong,
        d: *mut ::core::ffi::c_ulong,
    ) -> ::core::ffi::c_int;
}

extern "C" {
    pub fn Add256(
        a: *const ::core::ffi::c_ulong,
        b: *const ::core::ffi::c_ulong,
        cin: ::core::ffi::c_ulong,
        c: *mut ::core::ffi::c_ulong,
    ) -> ::core::ffi::c_int;
}
